/*	File: real1DTestSignal.h 
	
	Description:
		real 1-D FFT test signal functions.
	
	Copyright:
		Copyright (C) 2009 Apple Inc.  All rights reserved.
	
	Disclaimer:
		IMPORTANT:  This Apple software is supplied to you by Apple
		Computer, Inc. ("Apple") in consideration of your agreement to
		the following terms, and your use, installation, modification
		or redistribution of this Apple software constitutes acceptance
		of these terms.  If you do not agree with these terms, please
		do not use, install, modify or redistribute this Apple
		software.

		In consideration of your agreement to abide by the following
		terms, and subject to these terms, Apple grants you a personal,
		non-exclusive license, under Apple’s copyrights in this
		original Apple software (the "Apple Software"), to use,
		reproduce, modify and redistribute the Apple Software, with or
		without modifications, in source and/or binary forms; provided
		that if you redistribute the Apple Software in its entirety and
		without modifications, you must retain this notice and the
		following text and disclaimers in all such redistributions of
		the Apple Software.  Neither the name, trademarks, service
		marks or logos of Apple Computer, Inc. may be used to endorse
		or promote products derived from the Apple Software without
		specific prior written permission from Apple.  Except as
		expressly stated in this notice, no other rights or licenses,
		express or implied, are granted by Apple herein, including but
		not limited to any patent rights that may be infringed by your
		derivative works or by other works in which the Apple Software
		may be incorporated.

		The Apple Software is provided by Apple on an "AS IS" basis.
		APPLE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
		WITHOUT LIMITATION THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
		MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, REGARDING
		THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN
		COMBINATION WITH YOUR PRODUCTS.

		IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT,
		INCIDENTAL OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
		TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
		DATA, OR PROFITS; OR BUSINESS INTERRUPTION) ARISING IN ANY WAY
		OUT OF THE USE, REPRODUCTION, MODIFICATION AND/OR DISTRIBUTION
		OF THE APPLE SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY
		OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR
		OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE POSSIBILITY OF
		SUCH DAMAGE.
*/

/*
 * real1DTestSignal.h - generate 1-D real FFT test signal and its expected FFT. 
 *
 * Created 7/21/2008. 
 * Copyright 2008 by Apple, Inc. 
 */
 
#ifndef	_REAL_1D_TEST_SIGNAL_H_
#define _REAL_1D_TEST_SIGNAL_H_

#include <libMatrixFFT/MatrixFFT.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Callback function for progress reporting. The percentDone value is 
 * between 0 and 100, with 100 indicating "done". The 'arg' value is 
 * whatever is was passed along with the callback pointer to 
 * fftGenReal1DTestSignal() or fftGenReal1DTestSignalFFT().
 */
typedef void (*fftCallbackFcn)(void *arg, unsigned percentDone);

/* 
 * Generate 1-D real test signal in row order.
 *
 * x[j] = e^(-Mj) - 2e^(-2Mj), j = 0...N-1
 */
extern int fftGenReal1DTestSignal(
	FFTComplex		*buf,
	size_t			numSamples,			/* number of real samples */
	fftCallbackFcn	callback,			/* optional */
	void			*callbackArg);		/* optional */

/*
 * Analyze a 1-D real test signal in row order, comparing it against
 * the expected values. Return max delta (mxe) and RMSE between
 * actual and expected. 
 *
 * Used to analyze the errors after a round-trip FFT of the test signal 
 * generated by fftGenReal1DTestSignal().
 */
extern int fftAnalyzeReal1DTestSignal(
	FFTComplex		*buf,
	size_t			numSamples,			/* number of real samples */
	fftCallbackFcn	callback,			/* optional */
	void			*callbackArg,		/* optional */
	double			*mxe,				/* RETURNED */
	double			*rmse);				/* RETURNED */

/* 
 * Generate expected forward FFT of 1-D real test signal.
 *
 * X[k] = F(M, k) - 2F(2M, k)
 *
 * Were
 *
 * F(L, k) = (1 - e^(-LN)) * (1 - (e^(-L) * e^(2*pi*i*k/N)))
 *           -----------------------------------------------
 *                1 - (2e^(-L) * cos(2*k*pi)) + e^(-2L)
 *
 * We scale the "expected" FFT here by a factor of 2 to match the output 
 * of both our own 1-D FFT and vDSP. 
 *
 * Output can be on one of two formats, described here:
 */
typedef enum {
	ST1D_RowOrder,			// raw row order
	ST1D_Column,			// column order, same as MatrixFFT's native 1-D real
} SignalFormat1D;

extern int fftGenReal1DTestSignalFFT(
	MatrixFFTPlan	mfftPlan,
	FFTComplex		*buf,
	size_t			numSamples,			/* number of real samples */
	SignalFormat1D	format,				/* row, column, custom */
	fftCallbackFcn	callback,			/* optional */
	void			*callbackArg);		/* optional */

/*
 * Analyze forward FFT of 1-D real test signal, comparing it against
 * the expected values. Return max delta (mxe) and RMSE between
 * actual and expected. 
 *
 * Used to analyze the errors after a forward FFT applied to the output of 
 * fftGenReal1DTestSignal().
 */
extern int fftAnalyzeReal1DTestSignalFFT(
	MatrixFFTPlan	mfftPlan,
	FFTComplex		*buf,
	size_t			numSamples,			/* number of real samples */
	SignalFormat1D	format,				/* row, column, custom */
	fftCallbackFcn	callback,			/* optional */
	void			*callbackArg,		/* optional */
	double			*mxe,				/* RETURNED */
	double			*rmse);				/* RETURNED */

#ifdef __cplusplus
}
#endif

#endif	/* _REAL_1D_TEST_SIGNAL_H_ */
